server:
  port: 8089
  servlet:
    session:
      timeout: 30
spring:
  application:
    name: xxpay-app-settlement
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml


